data:
  image: jenkins:1.625.2
  command: /bin/true
  volumes:
    - /var/jenkins_home
master:
  #  image: reppard/buildbox-jenkins-master
  build: ./buildbox-jenkins-master
  ports:
    - "8080:8080"
    - "5000:5000"
  volumes_from:
    - data
swarm:
  #  image: reppard/buildbox-swarm-node
  build: ./buildbox-swarm-node
  links:
    - master
  environment:
    - NODE_NAME=BuildboxSwarmNode
    - NODE_LABEL=dev
    - NODE_EXECUTORS=2
seagull:
  image: tobegit3hub/seagull
  ports:
    - "65138:10086"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
